name: .NET CI/CD Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    PROJECT_NAME: "Host"
    DOTNET_VERSION: "10.0.x"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore

            - name: Build project
              run: dotnet build $PROJECT_NAME/$PROJECT_NAME.csproj -c Release --no-restore

            - name: Run tests
              run: dotnet test --no-build
